name: Scrape COMOLI Info

on:
  schedule:
    - cron: '0 4 * * *'  # 毎日04:00 UTCに実行（日本時間13:00）
  workflow_dispatch:  # 手動実行用

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools
          pip install -r requirements.txt

      - name: Verify environment variables
        run: |
          if [ -z "$LINE_CHANNEL_ACCESS_TOKEN" ]; then
            echo "Error: LINE_CHANNEL_ACCESS_TOKEN is not set"
            exit 1
          fi
          if [ -z "$LINE_USER_ID" ]; then
            echo "Error: LINE_USER_ID is not set"
            exit 1
          fi
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}

      - name: Run scraper
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: python scrape_comoli.py

      - name: Commit changes
        if: success()  # スクリプトが成功した場合のみ実行
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --staged --quiet || git commit -m "Update previous content"
          git push || echo "No changes to push" 