name: Scrape COMOLI Info

on:
  schedule:
    - cron: '0 4 * * *'  # 毎日04:00 UTCに実行（日本時間13:00）
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode (skip content comparison)'
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools
          pip install -r requirements.txt

      - name: Verify environment variables
        run: |
          if [ -z "$LINE_CHANNEL_ACCESS_TOKEN" ]; then
            echo "Error: LINE_CHANNEL_ACCESS_TOKEN is not set"
            exit 1
          fi
          if [ -z "$LINE_CHANNEL_SECRET" ]; then
            echo "Error: LINE_CHANNEL_SECRET is not set"
            exit 1
          fi
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}

      - name: Run scraper
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
        run: |
          if [ "${{ inputs.test_mode }}" = "true" ]; then
            python scrape_comoli.py --test
          else
            python scrape_comoli.py
          fi

      - name: Commit changes
        if: success() && inputs.test_mode != 'true'  # テストモードの場合はコミットをスキップ
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add previous_content.json
          git status
          git diff --staged
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update previous content"
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 